name: Check Types
run-name: ${{ github.actor }} is checking types...
on: [push]
jobs:
  Check-Types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Bun
        # You may pin to the exact commit or the version.
        # uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc
        uses: oven-sh/setup-bun@v1.1.1
        with:
          # The version of Bun to install. (e.g. "latest", "canary", "1.0.0", "1.0.x", <sha>)
          bun-version: latest
      - run: bun install
      - name: Check Types
        run: cd ./packages/concise-motion-core && bun run test
          
